### ISSUE TITLE
Login credentials

### ISSUE THREAD

**Issue by preciousimo** [preciousimo/studybud#3]
Please set login credentials to username instead of email.

**Comment by JolomonSon** [comment]
### Observations
Hello Precious!
Having gone through the **studybud project**, here are my following concerns:

- Try using descriptive names in naming/initializing variables, creating models, and so on (also apps that will be created during the course of development) for other collaborators to easily identify them.

- No doubt the **studybud project** has gone beyond the scope of it's original capacity (kudos to your brilliant idea) hence, it'll be appropriate we contribute directly to the repository in the **ADA Global Concept Organization** - [here](https://github.com/ADA-WebDevs/studybud).    Forking and Cloning should not be a problem

Your Contributions so far has been outstanding. Good Job.

**Comment by preciousimo** [comment]
Noted I'll start direct contribution to ADA Global Concept subsequently. 
Please have you fixed the login issue

**Comment by JolomonSon** [comment]
I realised there's more to be done than just "fixing the issue" as stated (Creating a separate app for user auth, admin dashboard and so on).
I'll close the issue as soon  as changes have been made

**Comment by JolomonSon** [comment]
### Suggestions
Hello Precious!

I've ben able to resolve the issue as requested, but the processes involved are not bearable.

I wouldn't want to outline my challenges faced because they actually improved my debugging skills.
The composition of the repository is complex and ambiguous thus I suggest our first line of action is a thorough optimization of the entire repository on/before stipulated date.
